apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app: {{ .Values.projectName }}
    environment: prod
---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:

    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
  labels:
    {{- include "enterprise-support.labels" . | nindent 4 }}
{{- end }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.projectName }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "enterprise-support.labels" . | nindent 4 }}
data:
  AWS_SSM_PATH: {{ .Values.config.ssmPath | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
