apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: worker
    {{- include "enterprise-support.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: worker
          image: {{ .Values.image.registry }}/{{ .Values.worker.image }}:{{ .Values.worker.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          envFrom:
            - configMapRef:
                name: {{ .Values.projectName }}-config
          livenessProbe:
            exec:
              command: ["python", "-c", "import boto3"]
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
