
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: enterprise-support
  namespace: argocd
spec:
  description: Support Desk platform — ticketing app (auth/ticket/assign/worker/frontend)

  sourceRepos:
    - "https://github.com/MNaveen0922/production-grade-3-tier-architecture.git"

  destinations:
    - namespace: enterprise-support
      server: https://kubernetes.default.svc


  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
